source: ./site
disable_disk_cache: true
exclude:
  - assets/ts/
keep_files:
  - assets/js/pedal-powered.js

title: Biking Across America
email: no-reply@bike-across-america.com
description: >-
  Follow the spectacular journey of four humans who have forgotten about motorized transport

baseurl: ""
url: "https://bike-across-america.com"
maps_api_key: null

sass:
  style: compressed
  sourcemap: always

# Build settings
# theme: minima
# plugins:
#   - jekyll-feed
