name: Location Checkin

on:
  workflow_dispatch:
    inputs:
      latitude:
        required: true
        description: The latitude value to be recorded
      longitude:
        required: true
        description: The longitude value to be recorded
      accuracy:
        required: false
        description: The reported accuracy of the lat/lng, typically provided as meters radius
      altitude:
        required: false
        description: The reported altitude of the coordinates, if the reporting tool supports

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
    
    - name: Record Info
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: | 
        node ./scripts/location-checkin.js ${{ github.event.inputs.latitude }} ${{ github.event.inputs.longitude }} ${{ github.event.inputs.accuracy }} ${{ github.event.inputs.altitude }}
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "updated location data with latest coordinates"
        git push
